"""add academic_integrity_score

Revision ID: 06d1a312becc
Revises: c5d2f62cc22e
Create Date: 2026-10-03 01:46:33.786898+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d1a312becc'
down_revision: Union[str, Sequence[str], None] = 'c5d2f62cc22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('academic_integrity_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'academic_integrity_score')
    # ### end Alembic commands ###
