"""baseline schema

Revision ID: 18d3ef8f020d
Revises: 
Create Date: 2026-07-21 00:23:34.510032+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d3ef8f020d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_allowlist',
    sa.Column('allowlist_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('allowlist_id')
    )
    op.create_index(op.f('ix_instructor_allowlist_allowlist_id'), 'instructor_allowlist', ['allowlist_id'], unique=False)
    op.create_index(op.f('ix_instructor_allowlist_email'), 'instructor_allowlist', ['email'], unique=True)
    op.create_table('otp_challenges',
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('registration', 'email_change')", name='ck_otp_purpose'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_otp_attempt_count'),
    sa.CheckConstraint('max_attempts > 0', name='ck_otp_max_attempts'),
    sa.CheckConstraint('resend_count >= 0', name='ck_otp_resend_count'),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    op.create_index(op.f('ix_otp_challenges_email'), 'otp_challenges', ['email'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'instructor')", name='ck_users_role'),
    sa.CheckConstraint('length(school_id) = 10', name='ck_users_school_id_length'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('academic_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('student_enrolled', 'enrollment_status_changed', 'activity_published', 'activity_updated', 'submission_created', 'submission_status_changed', 'grade_released', 'classroom_archived')", name='ck_academic_events_type'),
    sa.CheckConstraint("resource_type IN ('classroom', 'enrollment', 'task', 'submission', 'grade')", name='ck_academic_events_resource_type'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_key', name='uq_academic_events_event_key')
    )
    op.create_index(op.f('ix_academic_events_actor_user_id'), 'academic_events', ['actor_user_id'], unique=False)
    op.create_index('ix_academic_events_resource', 'academic_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_academic_events_type_occurred', 'academic_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('audit_records',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('audit_key', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('audit_data', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('user_registered', 'login_succeeded', 'login_failed', 'classroom_created', 'classroom_updated', 'classroom_archived', 'classroom_reactivated', 'student_enrolled', 'enrollment_status_changed', 'activity_created', 'activity_updated', 'activity_published', 'activity_unpublished', 'submission_created', 'submission_status_changed', 'grade_created', 'grade_updated', 'grade_released', 'notification_marked_read', 'notifications_marked_read')", name='ck_audit_records_action_type'),
    sa.CheckConstraint("outcome IN ('succeeded', 'denied', 'failed')", name='ck_audit_records_outcome'),
    sa.CheckConstraint("resource_type IN ('user', 'classroom', 'enrollment', 'task', 'submission', 'grade', 'notification')", name='ck_audit_records_resource_type'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_id'),
    sa.UniqueConstraint('audit_key', name='uq_audit_records_audit_key')
    )
    op.create_index('ix_audit_records_action_occurred', 'audit_records', ['action_type', 'occurred_at'], unique=False)
    op.create_index('ix_audit_records_actor_occurred', 'audit_records', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_records_actor_user_id'), 'audit_records', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_records_resource_occurred', 'audit_records', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_table('classrooms',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('class_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classrooms_class_code'), 'classrooms', ['class_code'], unique=True)
    op.create_index(op.f('ix_classrooms_class_id'), 'classrooms', ['class_id'], unique=False)
    op.create_index(op.f('ix_classrooms_instructor_id'), 'classrooms', ['instructor_id'], unique=False)
    op.create_table('pending_registrations',
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('school_id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('data_collection_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(school_id) = 10', name='ck_pending_registrations_school_id_length'),
    sa.ForeignKeyConstraint(['challenge_id'], ['otp_challenges.challenge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index(op.f('ix_pending_registrations_challenge_id'), 'pending_registrations', ['challenge_id'], unique=True)
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_pending_registrations_school_id'), 'pending_registrations', ['school_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'disabled', 'removed')", name='ck_enrollments_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.class_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_enrollment_class_student')
    )
    op.create_index(op.f('ix_enrollments_class_id'), 'enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_id'), 'enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['academic_events.event_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('event_id', 'recipient_id', name='uq_notifications_event_recipient')
    )
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_read_created', 'notifications', ['recipient_id', 'is_read', 'created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('required_ast_rules', sa.JSON(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('paste_policy', sa.String(length=20), nullable=False),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('laboratory', 'homework')", name='ck_tasks_activity_type'),
    sa.CheckConstraint("paste_policy IN ('internal_only', 'disabled')", name='ck_tasks_paste_policy'),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.class_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_class_id'), 'tasks', ['class_id'], unique=False)
    op.create_index(op.f('ix_tasks_instructor_id'), 'tasks', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('coding_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tab_switch_count', sa.Integer(), nullable=False),
    sa.Column('blocked_paste_count', sa.Integer(), nullable=False),
    sa.Column('run_attempt_count', sa.Integer(), nullable=False),
    sa.Column('idle_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('last_blocked_paste_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('blocked_paste_count >= 0', name='ck_sessions_blocked_paste'),
    sa.CheckConstraint('idle_duration_seconds >= 0', name='ck_sessions_idle_duration'),
    sa.CheckConstraint('run_attempt_count >= 0', name='ck_sessions_run_attempts'),
    sa.CheckConstraint('tab_switch_count >= 0', name='ck_sessions_tab_switches'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_coding_sessions_student_id'), 'coding_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_coding_sessions_task_id'), 'coding_sessions', ['task_id'], unique=False)
    op.create_table('task_test_cases',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('standard_input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_test_cases_display_order'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('test_case_id')
    )
    op.create_index(op.f('ix_task_test_cases_task_id'), 'task_test_cases', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_test_cases_test_case_id'), 'task_test_cases', ['test_case_id'], unique=False)
    op.create_table('submissions',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('coding_session_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('raw_code', sa.Text(), nullable=False),
    sa.Column('standard_input', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jaccard_score', sa.Float(), nullable=True),
    sa.Column('ast_pass_fail', sa.Boolean(), nullable=True),
    sa.CheckConstraint("status IN ('submitted', 'awaiting_review', 'graded', 'rejected')", name='ck_submissions_status'),
    sa.CheckConstraint('attempt_number > 0', name='ck_submission_attempt_number'),
    sa.ForeignKeyConstraint(['coding_session_id'], ['coding_sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sub_id'),
    sa.UniqueConstraint('student_id', 'task_id', 'attempt_number', name='uq_submission_attempt')
    )
    op.create_index(op.f('ix_submissions_coding_session_id'), 'submissions', ['coding_session_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_index('ix_submissions_student_task', 'submissions', ['student_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_submissions_sub_id'), 'submissions', ['sub_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_table('behavioral_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('tab_switches_count', sa.Integer(), nullable=False),
    sa.Column('blocked_paste_count', sa.Integer(), nullable=False),
    sa.Column('run_attempt_count', sa.Integer(), nullable=False),
    sa.Column('idle_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('last_blocked_paste_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocked_paste_count >= 0', name='ck_logs_blocked_paste'),
    sa.CheckConstraint('idle_duration_seconds >= 0', name='ck_logs_idle_duration'),
    sa.CheckConstraint('run_attempt_count >= 0', name='ck_logs_run_attempts'),
    sa.CheckConstraint('tab_switches_count >= 0', name='ck_logs_tab_switches'),
    sa.ForeignKeyConstraint(['sub_id'], ['submissions.sub_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('sub_id')
    )
    op.create_index(op.f('ix_behavioral_logs_log_id'), 'behavioral_logs', ['log_id'], unique=False)
    op.create_table('execution_requests',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('last_partner_sequence', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('coding_session_id', sa.String(length=36), nullable=True),
    sa.Column('request_kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('standard_input', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('limit_reason', sa.String(length=100), nullable=True),
    sa.Column('worker_task_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("request_kind IN ('run', 'check', 'submit')", name='ck_execution_request_kind'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'syntax_error', 'runtime_error', 'timed_out', 'memory_limit', 'output_limit', 'process_limit', 'cancelled', 'failed')", name='ck_execution_status'),
    sa.CheckConstraint('last_partner_sequence >= 0', name='ck_execution_last_partner_sequence'),
    sa.ForeignKeyConstraint(['coding_session_id'], ['coding_sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.sub_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('execution_id'),
    sa.UniqueConstraint('correlation_id', name='uq_execution_requests_correlation_id'),
    sa.UniqueConstraint('dispatch_idempotency_key', name='uq_execution_requests_dispatch_idempotency_key')
    )
    op.create_index(op.f('ix_execution_requests_coding_session_id'), 'execution_requests', ['coding_session_id'], unique=False)
    op.create_index(op.f('ix_execution_requests_correlation_id'), 'execution_requests', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_execution_requests_dispatch_idempotency_key'), 'execution_requests', ['dispatch_idempotency_key'], unique=False)
    op.create_index('ix_execution_requests_partner_state', 'execution_requests', ['status', 'last_partner_sequence'], unique=False)
    op.create_index(op.f('ix_execution_requests_status'), 'execution_requests', ['status'], unique=False)
    op.create_index(op.f('ix_execution_requests_student_id'), 'execution_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_execution_requests_submission_id'), 'execution_requests', ['submission_id'], unique=False)
    op.create_index(op.f('ix_execution_requests_task_id'), 'execution_requests', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_requests_worker_task_id'), 'execution_requests', ['worker_task_id'], unique=True)
    op.create_table('instructor_grades',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_grades_max_score_positive'),
    sa.CheckConstraint('score <= max_score', name='ck_grades_score_within_max'),
    sa.CheckConstraint('score >= 0', name='ck_grades_score_nonnegative'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.sub_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_index(op.f('ix_instructor_grades_grade_id'), 'instructor_grades', ['grade_id'], unique=False)
    op.create_index(op.f('ix_instructor_grades_instructor_id'), 'instructor_grades', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_grades_submission_id'), 'instructor_grades', ['submission_id'], unique=True)
    op.create_table('similarity_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('source_submission_id', sa.Integer(), nullable=False),
    sa.Column('compared_submission_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_similarity_score'),
    sa.ForeignKeyConstraint(['compared_submission_id'], ['submissions.sub_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_submission_id'], ['submissions.sub_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_similarity_results_compared_submission_id'), 'similarity_results', ['compared_submission_id'], unique=False)
    op.create_index(op.f('ix_similarity_results_result_id'), 'similarity_results', ['result_id'], unique=False)
    op.create_index(op.f('ix_similarity_results_source_submission_id'), 'similarity_results', ['source_submission_id'], unique=False)
    op.create_table('ast_analyses',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('overall_pass', sa.Boolean(), nullable=True),
    sa.Column('syntax_error', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_requests.execution_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.sub_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_ast_analyses_analysis_id'), 'ast_analyses', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ast_analyses_execution_id'), 'ast_analyses', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ast_analyses_submission_id'), 'ast_analyses', ['submission_id'], unique=False)
    op.create_table('partner_execution_updates',
    sa.Column('partner_update_record_id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'syntax_error', 'runtime_error', 'timed_out', 'memory_limit', 'output_limit', 'process_limit', 'cancelled', 'failed')", name='ck_partner_execution_updates_status'),
    sa.CheckConstraint('length(payload_digest) = 64', name='ck_partner_execution_updates_digest_length'),
    sa.CheckConstraint('sequence_number > 0', name='ck_partner_execution_updates_sequence'),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_requests.execution_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('partner_update_record_id'),
    sa.UniqueConstraint('execution_id', 'sequence_number', name='uq_partner_execution_updates_execution_sequence'),
    sa.UniqueConstraint('update_id', name='uq_partner_execution_updates_update_id')
    )
    op.create_index(op.f('ix_partner_execution_updates_correlation_id'), 'partner_execution_updates', ['correlation_id'], unique=False)
    op.create_index('ix_partner_execution_updates_correlation_sequence', 'partner_execution_updates', ['correlation_id', 'sequence_number'], unique=False)
    op.create_index('ix_partner_execution_updates_execution_accepted', 'partner_execution_updates', ['execution_id', 'accepted_at'], unique=False)
    op.create_index(op.f('ix_partner_execution_updates_execution_id'), 'partner_execution_updates', ['execution_id'], unique=False)
    op.create_index(op.f('ix_partner_execution_updates_partner_update_record_id'), 'partner_execution_updates', ['partner_update_record_id'], unique=False)
    op.create_table('ast_findings',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ast_analyses.analysis_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_ast_findings_analysis_id'), 'ast_findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ast_findings_finding_id'), 'ast_findings', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ast_findings_finding_id'), table_name='ast_findings')
    op.drop_index(op.f('ix_ast_findings_analysis_id'), table_name='ast_findings')
    op.drop_table('ast_findings')
    op.drop_index(op.f('ix_partner_execution_updates_partner_update_record_id'), table_name='partner_execution_updates')
    op.drop_index(op.f('ix_partner_execution_updates_execution_id'), table_name='partner_execution_updates')
    op.drop_index('ix_partner_execution_updates_execution_accepted', table_name='partner_execution_updates')
    op.drop_index('ix_partner_execution_updates_correlation_sequence', table_name='partner_execution_updates')
    op.drop_index(op.f('ix_partner_execution_updates_correlation_id'), table_name='partner_execution_updates')
    op.drop_table('partner_execution_updates')
    op.drop_index(op.f('ix_ast_analyses_submission_id'), table_name='ast_analyses')
    op.drop_index(op.f('ix_ast_analyses_execution_id'), table_name='ast_analyses')
    op.drop_index(op.f('ix_ast_analyses_analysis_id'), table_name='ast_analyses')
    op.drop_table('ast_analyses')
    op.drop_index(op.f('ix_similarity_results_source_submission_id'), table_name='similarity_results')
    op.drop_index(op.f('ix_similarity_results_result_id'), table_name='similarity_results')
    op.drop_index(op.f('ix_similarity_results_compared_submission_id'), table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_instructor_grades_submission_id'), table_name='instructor_grades')
    op.drop_index(op.f('ix_instructor_grades_instructor_id'), table_name='instructor_grades')
    op.drop_index(op.f('ix_instructor_grades_grade_id'), table_name='instructor_grades')
    op.drop_table('instructor_grades')
    op.drop_index(op.f('ix_execution_requests_worker_task_id'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_task_id'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_submission_id'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_student_id'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_status'), table_name='execution_requests')
    op.drop_index('ix_execution_requests_partner_state', table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_dispatch_idempotency_key'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_correlation_id'), table_name='execution_requests')
    op.drop_index(op.f('ix_execution_requests_coding_session_id'), table_name='execution_requests')
    op.drop_table('execution_requests')
    op.drop_index(op.f('ix_behavioral_logs_log_id'), table_name='behavioral_logs')
    op.drop_table('behavioral_logs')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_sub_id'), table_name='submissions')
    op.drop_index('ix_submissions_student_task', table_name='submissions')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_coding_session_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_task_test_cases_test_case_id'), table_name='task_test_cases')
    op.drop_index(op.f('ix_task_test_cases_task_id'), table_name='task_test_cases')
    op.drop_table('task_test_cases')
    op.drop_index(op.f('ix_coding_sessions_task_id'), table_name='coding_sessions')
    op.drop_index(op.f('ix_coding_sessions_student_id'), table_name='coding_sessions')
    op.drop_table('coding_sessions')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_instructor_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_class_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_notifications_recipient_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_class_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_pending_registrations_school_id'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_challenge_id'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    op.drop_index(op.f('ix_classrooms_instructor_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_class_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_class_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index('ix_audit_records_resource_occurred', table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_actor_user_id'), table_name='audit_records')
    op.drop_index('ix_audit_records_actor_occurred', table_name='audit_records')
    op.drop_index('ix_audit_records_action_occurred', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index('ix_academic_events_type_occurred', table_name='academic_events')
    op.drop_index('ix_academic_events_resource', table_name='academic_events')
    op.drop_index(op.f('ix_academic_events_actor_user_id'), table_name='academic_events')
    op.drop_table('academic_events')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_challenges_email'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_instructor_allowlist_email'), table_name='instructor_allowlist')
    op.drop_index(op.f('ix_instructor_allowlist_allowlist_id'), table_name='instructor_allowlist')
    op.drop_table('instructor_allowlist')
    # ### end Alembic commands ###
