"""Add PendingEnrollment and PracticeModule.instructor_id

Revision ID: 2cd5c3a3ee9a
Revises: 9ee0a4c7ee5e
Create Date: 2026-09-22 16:33:34.933229+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd5c3a3ee9a'
down_revision: Union[str, Sequence[str], None] = '9ee0a4c7ee5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_enrollments',
    sa.Column('pending_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.class_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pending_id'),
    sa.UniqueConstraint('class_id', 'email', name='uq_pending_enrollment_class_email')
    )
    op.create_index(op.f('ix_pending_enrollments_class_id'), 'pending_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_pending_enrollments_email'), 'pending_enrollments', ['email'], unique=False)
    op.create_index(op.f('ix_pending_enrollments_pending_id'), 'pending_enrollments', ['pending_id'], unique=False)
    op.add_column('practice_modules', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_practice_modules_instructor_id'), 'practice_modules', ['instructor_id'], unique=False)
    op.create_foreign_key(None, 'practice_modules', 'users', ['instructor_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_modules', type_='foreignkey')
    op.drop_index(op.f('ix_practice_modules_instructor_id'), table_name='practice_modules')
    op.drop_column('practice_modules', 'instructor_id')
    op.drop_index(op.f('ix_pending_enrollments_pending_id'), table_name='pending_enrollments')
    op.drop_index(op.f('ix_pending_enrollments_email'), table_name='pending_enrollments')
    op.drop_index(op.f('ix_pending_enrollments_class_id'), table_name='pending_enrollments')
    op.drop_table('pending_enrollments')
    # ### end Alembic commands ###
