"""Add performance indexes

Revision ID: 333fed79e9f7
Revises: cc57d32cd493
Create Date: 2026-09-26 11:29:58.526921+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333fed79e9f7'
down_revision: Union[str, Sequence[str], None] = 'cc57d32cd493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enrollments_class_student', 'enrollments', ['class_id', 'student_id'], unique=False)
    op.create_index('ix_submissions_task_student', 'submissions', ['task_id', 'student_id'], unique=False)
    op.create_index('ix_tasks_class_pub', 'tasks', ['class_id', 'is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_class_pub', table_name='tasks')
    op.drop_index('ix_submissions_task_student', table_name='submissions')
    op.drop_index('ix_enrollments_class_student', table_name='enrollments')
    # ### end Alembic commands ###
