"""Add scheduled_publish_at to Task

Revision ID: 4b7b10be9827
Revises: 9f2c6e4a1b7d
Create Date: 2026-08-10 13:48:21.307488+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7b10be9827'
down_revision: Union[str, Sequence[str], None] = '9f2c6e4a1b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_publish_at')
    # ### end Alembic commands ###
