"""Add solo practice models

Revision ID: 9ee0a4c7ee5e
Revises: 8d2f5e3c7a1b
Create Date: 2026-09-17 05:19:52.862150+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee0a4c7ee5e'
down_revision: Union[str, Sequence[str], None] = '8d2f5e3c7a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_modules',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_index(op.f('ix_practice_modules_module_id'), 'practice_modules', ['module_id'], unique=False)
    op.create_table('practice_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('expected_ast_patterns', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['practice_modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_practice_tasks_task_id'), 'practice_tasks', ['task_id'], unique=False)
    op.create_table('practice_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('execution_feedback', sa.Text(), nullable=True),
    sa.Column('ast_feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['practice_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_practice_attempts_attempt_id'), 'practice_attempts', ['attempt_id'], unique=False)
    op.create_table('practice_progress',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['practice_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('student_id', 'task_id', name='uq_practice_progress_student_task')
    )
    op.create_index(op.f('ix_practice_progress_progress_id'), 'practice_progress', ['progress_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_progress_progress_id'), table_name='practice_progress')
    op.drop_table('practice_progress')
    op.drop_index(op.f('ix_practice_attempts_attempt_id'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    op.drop_index(op.f('ix_practice_tasks_task_id'), table_name='practice_tasks')
    op.drop_table('practice_tasks')
    op.drop_index(op.f('ix_practice_modules_module_id'), table_name='practice_modules')
    op.drop_table('practice_modules')
    # ### end Alembic commands ###
