"""Add retake flags to Submission

Revision ID: 9ff2d118b666
Revises: 333fed79e9f7
Create Date: 2026-10-01 05:20:34.369303+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff2d118b666'
down_revision: Union[str, Sequence[str], None] = '333fed79e9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('retake_requested', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('submissions', sa.Column('retake_allowed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'retake_allowed')
    op.drop_column('submissions', 'retake_requested')
    # ### end Alembic commands ###
