"""Add ai_hint to PracticeAttempt

Revision ID: cc57d32cd493
Revises: 068b56b87330
Create Date: 2026-09-26 00:20:21.007440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc57d32cd493'
down_revision: Union[str, Sequence[str], None] = '068b56b87330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_attempts', sa.Column('ai_hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_attempts', 'ai_hint')
    # ### end Alembic commands ###
