"""add task difficulty

Revision ID: d43bb28f463d
Revises: 9ee0a4c7ee5e
Create Date: 2026-09-21 08:17:57.296760+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43bb28f463d'
down_revision: Union[str, Sequence[str], None] = '9ee0a4c7ee5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('difficulty', sa.String(length=20), server_default='beginner', nullable=False))
    
    op.create_check_constraint(
        "ck_tasks_difficulty",
        "tasks",
        "difficulty IN ('beginner', 'intermediate', 'expert')"
    )

    # Fix legacy JSON rules for list and dict comprehensions
    op.execute("""
        UPDATE tasks
        SET required_ast_rules = (required_ast_rules::jsonb - 'require_list_comp' || jsonb_build_object('require_list_comprehension', required_ast_rules::jsonb -> 'require_list_comp'))::json
        WHERE required_ast_rules::jsonb ? 'require_list_comp';
    """)
    op.execute("""
        UPDATE tasks
        SET required_ast_rules = (required_ast_rules::jsonb - 'require_dict_comp' || jsonb_build_object('require_dict_comprehension', required_ast_rules::jsonb -> 'require_dict_comp'))::json
        WHERE required_ast_rules::jsonb ? 'require_dict_comp';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'difficulty')
    # ### end Alembic commands ###
