"""Add ast_strictness_level

Revision ID: e2b33e751f23
Revises: d43bb28f463d
Create Date: 2026-09-22 01:52:12.752694+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b33e751f23'
down_revision: Union[str, Sequence[str], None] = 'd43bb28f463d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ast_strictness_level', sa.String(length=20), server_default='moderate', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ast_strictness_level')
    # ### end Alembic commands ###
